version: "3"
services:
  python:
    build: ./server
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./server:/usr/src/app
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      - sqldb
      - mongodb
  node:
    build: ./nlp
    volumes:
      - ./nlp:/usr/src/app
    ports:
      - 5001:5001
    restart: on-failure
  sqldb:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=UCL
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - sql-db-data:/var/lib/postgresql/data
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-db-data:/data/db
volumes:
  mongo-db-data:
  sql-db-data:
